# Generated by Django 5.0.6 on 2024-06-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_name", models.CharField(max_length=100)),
                ("strategy_name", models.CharField(max_length=100)),
                ("signal", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("price", models.FloatField()),
                ("final_portfolio_value", models.FloatField()),
            ],
        ),
    ]
